// <auto-generated />
using Coffer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coffer.Migrations
{
    [DbContext(typeof(CofferDBContext))]
    partial class CofferDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coffer.Models.Coffer", b =>
                {
                    b.Property<string>("added")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citylat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citylng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("end_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("impact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("intensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("likelihood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pestle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("published")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relevance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("start_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("swot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Coffers");
                });
#pragma warning restore 612, 618
        }
    }
}
